import {
  getFirestore,
  collection,
  query,
  orderBy,
  limit,
  doc,
  where,
  getDocs,
  getDoc,
} from "firebase/firestore";
import { initializeApp } from "firebase/app";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import AgendaCard from "../components/agendaCard";
import styles from "../styles/Home.module.css";
import { useRecoilState, useRecoilValue } from "recoil";
import { communityState, searchIsClicked } from "../components/recoil/recoil";
import logo from "../public/국민찬반.svg";

export async function getStaticProps() {
  initializeApp({
    apiKey: process.env.apiKey,
    authDomain: process.env.authDomain,
    projectId: process.env.projectId,
    storageBucket: process.env.storageBucket,
    messagingSenderId: process.env.messagingSenderId,
    appId: process.env.appId,
    measurementId: process.env.measurementId,
  });
  const db = getFirestore();
  // 투표수 상위 10개 내림차순
  const agendaRef = query(collection(db, "agenda"));
  const q = query(agendaRef, orderBy("numVote", "desc"), limit(10));
  const agendaSnapshot = await getDocs(q);

  let agendas = [];

  agendaSnapshot.forEach(async (document) => {
    console.log(document.id);
    agendas.push({
      id: document.id,
      ...document.data(),
    });
  });

  const agendasData = JSON.stringify(agendas);

  return {
    props: {
      agendasData,
    },
    revalidate: 15,
  };
}

export default function Home({ agendasData }) {
  // const db = getFirestore();
  const [isClicked, setIsClicked] = useRecoilState(searchIsClicked);
  const [community, setCommunity] = useRecoilState(communityState);

  useEffect(() => {
    setIsClicked(false);
    // fetchData();
    setCommunity("agenda");
  }, []);

  let agendas = JSON.parse(agendasData);

  return (
    <div className={styles.container}>
      <Head>
        <title>성숙한 대한민국! | 국민찬반</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ICON.ico" />
      </Head>

      <main className={styles.main}>
        <span className={styles.logoContainer}>
          <Image src={logo} alt="국민찬반" height={75} width={270} />
        </span>
        <div className={styles.cardSection}>
          {agendas?.map((data) => {
            return (
              <div key={data.id}>
                <Link
                  href={{
                    pathname: `/agenda/${data.id}`,
                    query: { agenda: JSON.stringify(data) },
                  }}
                  as={`/agenda/${data.id}`}
                >
                  <a>
                    <AgendaCard props={data} />
                  </a>
                </Link>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
}
